name       : python-pafy
version    : 0.5.5
release    : 8
source     :
    - https://github.com/mps-youtube/pafy/releases/download/v0.5.5/pafy-0.5.5.tar.gz : 364f1d1312c89582d97dc7225cf6858cde27cb11dfd64a9c2bab1a2f32133b1e
homepage   : https://github.com/mps-youtube/pafy
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Python API for YouTube
description: |
    Python library to download YouTube content and retrieve metadata.
builddeps  :
    - yt-dlp
rundeps    :
    - yt-dlp
setup      : |
    %patch -p1 < $pkgfiles/0001-Replace-youtube-dl-with-yt-dlp.patch
build      : |
    %python3_setup
install    : |
    %python3_install
