name       : python-pafy
version    : 0.5.4
release    : 1
source     :
    - https://github.com/mps-youtube/pafy/archive/v0.5.4.tar.gz : a2f9fe7c6175264993190081e1558516b2f2b5987f13a581a55cd9d838df973b
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Python API for YouTube
description: |
    Python API for YouTube
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - youtube-dl
rundeps    :
    - youtube-dl
build      : |
    %python3_setup
install    : |
    %python3_install
